Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config une première VM "Gitea"
  config.vm.define "gitea" do |gitea|
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    gitea.vm.network "private_network", ip: "192.168.4.11"
  
    gitea.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "gitea.tp4.b2"
    end

    gitea.vm.provision "shell", path: "scripts/install_all.sh"
    gitea.vm.provision "shell", path: "scripts/install_gitea.sh"
  end

  # Config une première VM "Nginx"
  config.vm.define "nginx" do |nginx|
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    nginx.vm.network "private_network", ip: "192.168.4.12"

    nginx.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "nginx.tp4.b2"
    end

    nginx.vm.provision "shell", path: "scripts/install_all.sh"
    nginx.vm.provision "shell", path: "scripts/install_nginx.sh"
  end

  # Config une première VM "NFS"
  config.vm.define "nfs" do |nfs|
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    nfs.vm.network "private_network", ip: "192.168.4.13"

    nfs.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "nfs.tp4.b2"
    end

    nfs.vm.provision "shell", path: "scripts/install_all.sh"
    nfs.vm.provision "shell", path: "scripts/install_nfs.sh"
  end

    # Config une première VM "BDD"
  config.vm.define "bdd" do |bdd|
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    bdd.vm.network "private_network", ip: "192.168.4.14"

    bdd.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "bdd.tp4.b2"
    end

    bdd.vm.provision "shell", path: "scripts/install_all.sh"
    bdd.vm.provision "shell", path: "scripts/install_bdd.sh"
  end

end